export const locations = [
  { id: "2", name: "정문건너편" },
  { id: "3", name: "우정원" },
  { id: "4", name: "공과대학" },
  { id: "5", name: "외국어대학" },
  { id: "6", name: "멀티미디어관" },
  { id: "7", name: "예술관" },
  { id: "8", name: "제2기숙사" },
  { id: "9", name: "체육대학" },
  { id: "10", name: "전자정보대학" },
  { id: "11", name: "예술디자인대학" },
  { id: "12", name: "중앙도서관" },
  { id: "13", name: "경영대학" },
  { id: "15", name: "생명대학" },
  { id: "16", name: "학생회관" },
  { id: "17", name: "선승관" },
  { id: "18", name: "국제대학" },
  { id: "19", name: "사색의광장" },
];
